Fix Clippy unsafe warnings that affects users
The proc macro that generates code was generating major Clippy lint
warnings for users for the crate, which is hard to work around as every
call-site has to have `#[allow(clippy::xxx)]´.

This fixes the main Clippy warning in this crate instead.
Would be fantastic to fix the rest also and enable Clippy in CI as well,
but that can be done as a separate change.

Here is how the warnings looked like for a user of the crate with the latest version:

```
error: this public function might dereference a raw pointer but is not marked `unsafe`
  --> api/api/src/api/resource.rs:82:62
   |
82 | #[cfg_attr(feature = "with_speedy", derive(speedy::Writable, speedy::Readable))]
   |                                                              ^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
   = note: this error originates in the derive macro `speedy::Readable` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Here is an example of Clippy warnings this resolves:

```
warning: transmute from a `f64` to a `u64`
  --> src/writer.rs:86:35
   |
86 |         let value: u64 = unsafe { mem::transmute( value ) };
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `value.to_bits()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#transmute_float_to_int

error: calling `set_len()` immediately after reserving a buffer creates uninitialized values
   --> src/circular_buffer.rs:218:9
    |
218 |         let mut buffer = Vec::with_capacity( capacity );
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
219 |         unsafe {
220 |             buffer.set_len( capacity );
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: initialize the buffer or wrap the content in `MaybeUninit`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec

    error: this public function might dereference a raw pointer but is not marked `unsafe`
    --> src/readable_impl.rs:141:82
     |
 141 |                     std::ptr::write_unaligned( itself, std::ptr::read_unaligned( itself ).swap_bytes() );
     |                                                                                  ^^^^^^
 ...
 165 | impl_for_primitive!( f64, read_f64, swap_slice_f64 );
     | ---------------------------------------------------- in this macro invocation
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
     = note: this error originates in the macro `impl_for_primitive` (in Nightly builds, run with -Z macro-backtrace for more info)

 warning: this lifetime isn't used in the impl
   --> src/readable.rs:282:7
    |
282 | impl< 'a, C, S > StreamReader< C, S > where C: Context, S: Read {
    |       ^^
    |
    = note: `#[warn(clippy::extra_unused_lifetimes)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
```